/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#faf9fd',
        surface: '#faf9fd',
        'surface-bright': '#faf9fd',
        'surface-dim': '#dad9dd',
        'surface-variant': '#e3e2e6',
        'surface-container': '#efedf1',
        'surface-container-low': '#f4f3f7',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e3e2e6',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1a1c1e',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#43474e',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        'border-subtle': '#c4c6cf',
        primary: '#002045',
        'primary-container': '#1a365d',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#adc7f7',
        'on-primary': '#ffffff',
        'on-primary-container': '#86a0cd',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#2d476f',
        secondary: '#0a6c44',
        'secondary-container': '#9ff5c1',
        'secondary-fixed': '#9ff5c1',
        'secondary-fixed-dim': '#83d8a6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#167249',
        'on-secondary-fixed': '#002111',
        'on-secondary-fixed-variant': '#005231',
        tertiary: '#371800',
        'tertiary-container': '#572900',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#e88532',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        'inverse-primary': '#adc7f7',
        'surface-tint': '#455f88',
        'status-available': '#2f855a',
        'status-off-season': '#718096',
        'status-pending': '#ed8936',
        'status-cancelled': '#e53e3e',
        'attraction-marker': '#805ad5',
        'map-overlay-dark': '#1a202c',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'collapsed-sidebar-width': '64px',
        'sidebar-width': '360px',
        'stack-gap': '0.75rem',
        'container-padding': '1.5rem',
        gutter: '1rem',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'mono-label': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-label': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
};
